version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_volume:/data/db

# docker exec -it my-mongo bash
volumes:
  mongo_volume:
    external: true
