import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/components/Providers'
import InputModal from '@/components/InputModal'
import AlertModal from '@/components/AlertModal'


export const metadata: Metadata = {
  title: 'NextJS + Mongoose Demo',
  description: 'Generated by NextJS + Mongoose'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
    <body>
      <Providers>
        <AlertModal />
        <InputModal />
        {children}
      </Providers>
    </body>
    </html>
  )
}
