import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/components/Providers'
import ReactModal from 'react-modal'
import CustomModal from '@/components/CustomModal'


export const metadata: Metadata = {
  title: 'NextJS + Mongoose Demo',
  description: 'Generated by NextJS + Mongoose'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
    <body>
      <Providers>
        <CustomModal />
        {children}
      </Providers>
    </body>
    </html>
  )
}
